version: '3'
services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    volumes:
      - n8n-data:/mnt/data  # This is where the SQLite database will be stored persistently
    environment:
      - N8N_DATABASE_SQLITE_FILE=/mnt/data/n8n.sqlite
    restart: always

volumes:
  n8n-data:
    driver: local
